sudo: required 
services:
 - docker

before_install:
 - docker build -t adnanalnayb/docker-react -f Dockerfile.dev .
 

script:
 - docker run -e CI=true adnanalnayb/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-React"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-876315032038"
  bucket_path: "Docker-React"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY 
  secret_access_key: "$AWS_SECRET_KEY"


