sudo: required 
services:
 - docker

before_install:
 - docker build -t adnanalnayb/docker-react -f Dockerfile.dev .
 

script:
 - docker run -e CI=true adnanalnayb/docker-react npm run test -- --coverage
